//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNODiscordBot; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class UNODiscordEmojis {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal UNODiscordEmojis() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UNODiscordBot.UNODiscordEmojis", typeof(UNODiscordEmojis).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 746444081424760943.
    /// </summary>
    internal static string BackCard {
        get {
            return ResourceManager.GetString("BackCard", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955401897246721.
    /// </summary>
    internal static string Blue_0 {
        get {
            return ResourceManager.GetString("Blue 0", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955411887816714.
    /// </summary>
    internal static string Blue_1 {
        get {
            return ResourceManager.GetString("Blue 1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955419764719626.
    /// </summary>
    internal static string Blue_2 {
        get {
            return ResourceManager.GetString("Blue 2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955428727947284.
    /// </summary>
    internal static string Blue_3 {
        get {
            return ResourceManager.GetString("Blue 3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955436139544640.
    /// </summary>
    internal static string Blue_4 {
        get {
            return ResourceManager.GetString("Blue 4", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955445169881138.
    /// </summary>
    internal static string Blue_5 {
        get {
            return ResourceManager.GetString("Blue 5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955453335928870.
    /// </summary>
    internal static string Blue_6 {
        get {
            return ResourceManager.GetString("Blue 6", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955460701388830.
    /// </summary>
    internal static string Blue_7 {
        get {
            return ResourceManager.GetString("Blue 7", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955468284559380.
    /// </summary>
    internal static string Blue_8 {
        get {
            return ResourceManager.GetString("Blue 8", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955477063237653.
    /// </summary>
    internal static string Blue_9 {
        get {
            return ResourceManager.GetString("Blue 9", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955485066100746.
    /// </summary>
    internal static string Blue_PlusTwo {
        get {
            return ResourceManager.GetString("Blue PlusTwo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955984477552653.
    /// </summary>
    internal static string Blue_Reverse {
        get {
            return ResourceManager.GetString("Blue Reverse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955996041248780.
    /// </summary>
    internal static string Blue_Skip {
        get {
            return ResourceManager.GetString("Blue Skip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955280916611084.
    /// </summary>
    internal static string Green_0 {
        get {
            return ResourceManager.GetString("Green 0", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955290123239445.
    /// </summary>
    internal static string Green_1 {
        get {
            return ResourceManager.GetString("Green 1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955297974714369.
    /// </summary>
    internal static string Green_2 {
        get {
            return ResourceManager.GetString("Green 2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955305839296562.
    /// </summary>
    internal static string Green_3 {
        get {
            return ResourceManager.GetString("Green 3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955311648276500.
    /// </summary>
    internal static string Green_4 {
        get {
            return ResourceManager.GetString("Green 4", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955324864528385.
    /// </summary>
    internal static string Green_5 {
        get {
            return ResourceManager.GetString("Green 5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955334033276960.
    /// </summary>
    internal static string Green_6 {
        get {
            return ResourceManager.GetString("Green 6", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955343843622923.
    /// </summary>
    internal static string Green_7 {
        get {
            return ResourceManager.GetString("Green 7", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955351926177812.
    /// </summary>
    internal static string Green_8 {
        get {
            return ResourceManager.GetString("Green 8", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955360570638369.
    /// </summary>
    internal static string Green_9 {
        get {
            return ResourceManager.GetString("Green 9", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955374319566877.
    /// </summary>
    internal static string Green_PlusTwo {
        get {
            return ResourceManager.GetString("Green PlusTwo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955383999889448.
    /// </summary>
    internal static string Green_Reverse {
        get {
            return ResourceManager.GetString("Green Reverse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955391277137931.
    /// </summary>
    internal static string Green_Skip {
        get {
            return ResourceManager.GetString("Green Skip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672954923008131122.
    /// </summary>
    internal static string Red_0 {
        get {
            return ResourceManager.GetString("Red 0", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672954938409615383.
    /// </summary>
    internal static string Red_1 {
        get {
            return ResourceManager.GetString("Red 1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955019666128946.
    /// </summary>
    internal static string Red_2 {
        get {
            return ResourceManager.GetString("Red 2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955040058834954.
    /// </summary>
    internal static string Red_3 {
        get {
            return ResourceManager.GetString("Red 3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955053639991337.
    /// </summary>
    internal static string Red_4 {
        get {
            return ResourceManager.GetString("Red 4", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955063106404411.
    /// </summary>
    internal static string Red_5 {
        get {
            return ResourceManager.GetString("Red 5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955071000215553.
    /// </summary>
    internal static string Red_6 {
        get {
            return ResourceManager.GetString("Red 6", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955078142853141.
    /// </summary>
    internal static string Red_7 {
        get {
            return ResourceManager.GetString("Red 7", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955085919092748.
    /// </summary>
    internal static string Red_8 {
        get {
            return ResourceManager.GetString("Red 8", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955093489811467.
    /// </summary>
    internal static string Red_9 {
        get {
            return ResourceManager.GetString("Red 9", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955105590509595.
    /// </summary>
    internal static string Red_PlusTwo {
        get {
            return ResourceManager.GetString("Red PlusTwo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955116407619595.
    /// </summary>
    internal static string Red_Reverse {
        get {
            return ResourceManager.GetString("Red Reverse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955128281563146.
    /// </summary>
    internal static string Red_Skip {
        get {
            return ResourceManager.GetString("Red Skip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672956016542875681.
    /// </summary>
    internal static string Wild_PlusFour {
        get {
            return ResourceManager.GetString("Wild PlusFour", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672956006158041126.
    /// </summary>
    internal static string Wild_Simple {
        get {
            return ResourceManager.GetString("Wild Simple", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955142232080404.
    /// </summary>
    internal static string Yellow_0 {
        get {
            return ResourceManager.GetString("Yellow 0", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955153032282122.
    /// </summary>
    internal static string Yellow_1 {
        get {
            return ResourceManager.GetString("Yellow 1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955162494500864.
    /// </summary>
    internal static string Yellow_2 {
        get {
            return ResourceManager.GetString("Yellow 2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955172355440651.
    /// </summary>
    internal static string Yellow_3 {
        get {
            return ResourceManager.GetString("Yellow 3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955181729579008.
    /// </summary>
    internal static string Yellow_4 {
        get {
            return ResourceManager.GetString("Yellow 4", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955193968820235.
    /// </summary>
    internal static string Yellow_5 {
        get {
            return ResourceManager.GetString("Yellow 5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955205025005572.
    /// </summary>
    internal static string Yellow_6 {
        get {
            return ResourceManager.GetString("Yellow 6", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955215166701598.
    /// </summary>
    internal static string Yellow_7 {
        get {
            return ResourceManager.GetString("Yellow 7", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955225396477973.
    /// </summary>
    internal static string Yellow_8 {
        get {
            return ResourceManager.GetString("Yellow 8", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955235005759508.
    /// </summary>
    internal static string Yellow_9 {
        get {
            return ResourceManager.GetString("Yellow 9", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955248784179208.
    /// </summary>
    internal static string Yellow_PlusTwo {
        get {
            return ResourceManager.GetString("Yellow PlusTwo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955258598850589.
    /// </summary>
    internal static string Yellow_Reverse {
        get {
            return ResourceManager.GetString("Yellow Reverse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 672955269512167454.
    /// </summary>
    internal static string Yellow_Skip {
        get {
            return ResourceManager.GetString("Yellow Skip", resourceCulture);
        }
    }
}
